services:
  users_app_postgres:
    container_name: users_app_postgres
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  users_app:
    container_name: users_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: true
    depends_on:
      users_app_postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
